package com.livestream.qos;

public enum QoSEventType {
    STREAM_STARTED,
    STREAM_STOPPED,
    STREAM_ZOMBIE_STOP,

    INGEST_UNSTABLE,
    INGEST_RECOVERED,
    INGEST_STALL,
    INGEST_NO_PATH,

    ENCODE_STARTED,
    ENCODE_RESTART,
    ENCODE_SLOW,
    ENCODE_ERROR,
    ENCODE_DEGRADED,
    ENCODE_RESTORED,

    DELIVERY_STALL,
    DELIVERY_ICE_FAILED,
    DELIVERY_ABR_STEP_DOWN,
    DELIVERY_ABR_STEP_UP,
    DELIVERY_RECONNECT,
    DELIVERY_RECOVERED,

    VIEWER_JOIN_OK,
    VIEWER_JOIN_FAIL,
    VIEWER_TTFF,
    VIEWER_STALL,
    VIEWER_FATAL,
    VIEWER_LEAVE,

    ALERT_RAISED
}
